# Generated by Django 3.2.3 on 2022-06-10 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='last_name',
            new_name='lastName',
        ),
    ]
