# Generated by Django 3.2.3 on 2022-06-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20220610_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
