# Generated by Django 3.2.3 on 2022-06-11 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20220611_1108'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BooksModel',
            new_name='Book',
        ),
    ]
