# Generated by Django 3.2.3 on 2022-06-12 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20220612_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='book',
            new_name='book_id',
        ),
    ]
