# Generated by Django 3.2.3 on 2022-06-13 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_book_stock_book_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='author_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authors', to='store.author'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='book_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='store.book'),
        ),
    ]
